### 회원가입 (고객)
POST http://localhost:8081/signup/customer
Content-Type: application/json

{
  "birth": "2023-06-10",
  "email": "example@gmail.com",
  "name": "name",
  "password": "password",
  "phone": "01012345678"
}

### 이메일 인증 (고객)
GET http://localhost:8081/signup/customer/verify?email=example@gmail.com&code=verifycode

### 로그인 (고객)
POST http://localhost:8081/signin/customer
Content-Type: application/json

{
  "email": "example@gmail.com",
  "password": "password"
}

### 회원 정보 조회 (고객)
GET http://localhost:8081/customer/getInfo
Content-Type: application/json
X-AUTH-TOKEN: JWT_TOKEN

### 잔액 변경 (고객)
POST http://localhost:8081/customer/balance
Content-Type: application/json
X-AUTH-TOKEN: JWT_TOKEN

{
  "from": "server",
  "message": "머니 충전",
  "money": 10000
}

########################

### 회원가입 (셀러)
POST http://localhost:8081/signup/seller
Content-Type: application/json

{
  "birth": "2023-06-10",
  "email": "example@gmail.com",
  "name": "name",
  "password": "password",
  "phone": "01012345678"
}

### 이메일 인증 (셀러)
GET http://localhost:8081/signup/seller/verify?email=example@gmail.com&code=verifycode

### 로그인 (셀러)
POST http://localhost:8081/signin/seller
Content-Type: application/json

{
  "email": "example@gmail.com",
  "password": "password"
}